export enum ActivityType {
  INAUGURAL_CLASS = ('Aula Inaugural'),
  MAGNA_CLASS = ('Aula Magna'),
  CERTIFICATION = ('Certificação'),
  COURSE = ('Curso'),
  GRADUATION = ('Colação de grau'),
  MEETING = ('Encontro'),
  EXHIBITION = ('Exposição'),
  FAIR = ('Feira'),
  GYMKHANA = ('Gincana'),
  OPENING = ('Inauguração'),
  ROUND_TABLE = ('Mesa Redonda'),
  MINI_COURSE = ('Minicurso'),
  CULTURAL_SHOW = ('Mostra cultural'),
  MUSICAL = ('Musical'),
  WORKSHOP = ('Oficina'),
  OLYMPICS = ('Olimpíada'),
  OTHER = ('Outros'),
  TALK = ('Palestra'),
  PANEL = ('Painel'),
  POSSESSION = ('Posse'),
  SEMINAR = ('Seminário'),
  TECHNICAL_VISIT = ('Visita Técnica'),
  WEBINAR = ('Webinar'),
  WORK_PRESENTATION = ('Apresentação de Trabalhos'),
}
